config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :images, only: :update
  end

  resources :folders

  resources :notes, except: %i[show destroy] do
    collection do
      patch 'reorder'
    end
  end

  root 'images#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
class Folder < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  acts_as_list sequential_update: false

  validates_presence_of :title, :description
  validates :position, uniqueness: { scope: :user }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes, dependent: :destroy
end

app/controllers/api/images_controller.rb
module Api
  class ImagesController < ApplicationController
    def update
      @image = Image.find params[:id]

      @image.update! title: params[:image][:title].strip

      head :ok
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder!, only: %i[edit update show destroy]

  def index
    @folders = Folder.order created_at: :desc
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new folder_params
    if @folder.save
      flash.now[:success] = 'Folder created!'
      # redirect_to folders_path
    else
      render :new
    end
  end

  def show; end

  def destroy
    @folder.destroy
    flash.now[:success] = 'Folder deleted!'
  end

  def edit; end

  def update
    if @folder.update folder_params
      # redirect_to folders_path
    else
      render :edit
    end
  end

  private

  def folder_params
    params.require(:folder).permit(:title, :description)
  end

  def set_folder!
    @folder = Folder.find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = current_user.notes.order(position: :asc)
  end

  def new
    @note = current_user.notes.build
    @note.position = current_user.notes.count + 1
  end

  def create
    @note = current_user.notes.build note_params
    if @note.save
      flash.now[:success] = 'Note created!'
    else
      render :new
    end
  end

  def edit
    @note = current_user.notes.find params[:id]
  end

  def update
    @note = current_user.notes.find params[:id]
    if @note.update note_params
      flash.now[:success] = 'Note updated!'
    else
      render :edit
    end
  end

  def reorder
    @note = current_user.notes.find_by position: params[:old_position]
    @note.insert_at params[:new_position]

    head :ok
  end

  private

  def note_params
    params.require(:note).permit(:title, :description, :position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def prepend_flash
    turbo_stream.prepend 'flash', partial: 'shared/flash'
  end
end

app/views/folders/_folder.html.erb
<%= turbo_frame_tag folder do %>
  <section class="mb-4">
    <h2><%= link_to folder.title, folder_path(folder), data: { turbo_frame: '_top' } %></h2>

    <p><%= folder.description %></p>

    <%= turbo_frame_tag folder do %>
      <%= link_to 'Edit', edit_folder_path(folder), class: 'btn btn-primary' %>
    <% end %>

    <%= link_to 'Delete', folder_path(folder), class: "btn btn-danger", data: { turbo_method: :delete } %>
  </section>
<% end %>

app/views/folders/_form.html.erb
<%= turbo_frame_tag folder do %>
  <%= form_with model: folder  do |f| %>
    <%= render 'shared/errors', object: folder %>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title, for: dom_id(folder, :title) %>
      </div>

      <div class="col-sm-10">
        <%= f.text_field :title, id: dom_id(folder, :title), class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description, for: dom_id(folder, :description) %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :description, id: dom_id(folder, :description), class: 'form-control' %>
      </div>
    </div>

    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/folders/create.turbo_stream.erb
<%= turbo_stream.update Folder.new, '' %>
<%= turbo_stream.after Folder.new, render(@folder) %>
<%= prepend_flash %>

app/views/folders/destroy.turbo_stream.erb
<%= turbo_stream.remove @folder %>
<%= prepend_flash %>

app/views/folders/edit.html.erb
<h1>Edit folder</h1>

<%= render 'form', folder: @folder %>

app/views/folders/index.html.erb
<h1>Folders</h1>

<%= link_to 'Add Folder', new_folder_path, class: 'btn btn-primary',
  data: { turbo_frame: dom_id(Folder.new) } %>

<%= turbo_frame_tag Folder.new %>

<%= render @folders %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form', folder: @folder %>

app/views/folders/show.html.erb
<h1><%= @folder.title %></h1>

<p><%= @folder.description %></p>

<%= link_to 'back to all folders', folders_path, class: 'btn btn-secondary' %>

app/views/folders/update.turbo_stream.erb
<%= turbo_stream.replace @folder, render(@folder) %>
<%= prepend_flash %>

app/views/images/index.html.erb
<h1>Images</h1>

<% @images.each do |image| %>
  <%= tag.section class: 'my-5',
    data: { controller: 'images toast', 'action': 'images:copy->toast#show',
      'images-loading-class': 'disabled', 'images-id-value': image.id } do %>
    <%= image_tag image.url, class: 'img-thumbnail rounded d-block',
      alt: image.title, data: { 'action': 'click->images#getUrl',
        'images-target': 'image' } %>
  <% end %>
<% end %>

<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="copyToast" class="toast">
    <div class="toast-header">
      <strong class="me-auto">Hey!</strong>
      <button type="button" class="btn-close" data-bs-dismiss="toast"></button>
    </div>

    <div class="toast-body">Text</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container">
      <div id="flash">
        <%= render 'shared/flash' %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<%= turbo_frame_tag note do %>
  <%= form_with model: note  do |f| %>
    <%= render 'shared/errors', object: note %>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title, for: dom_id(note, :title) %>
      </div>

      <div class="col-sm-10">
        <%= f.text_field :title, id: dom_id(note, :title), class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description, for: dom_id(note, :description) %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :description, id: dom_id(note, :description), class: 'form-control' %>
      </div>
    </div>

    <% if note.new_record? %>
      <div class="mb-3 row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :position, for: dom_id(note, :position) %>
        </div>

        <div class="col-sm-10">
          <%= f.number_field :position, id: dom_id(note, :position), class: 'form-control', readonly: true %>
        </div>
      </div>
    <% end %>

    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/notes/_note.html.erb
<%= turbo_frame_tag note, class: 'item' do %>
  <section class="mt-3">
    <h2>
      <i class="bi bi-arrows-move js-sort-handle fs-3"></i>
        <%= note.title %>
    </h2>

    <p class="lead">
      <span class="badge bg-info" data-sortable-target="position">
        <%= note.position %>
      </span>

      <%= note.description %>
    </p>

    <%= turbo_frame_tag note do %>
      <%= link_to 'Edit', edit_note_path(note), class: 'btn btn-secondary' %>
    <% end %>
  </section>
<% end %>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.update Note.new, '' %>
<%= turbo_stream.append 'notes', render(@note) %>
<%= prepend_flash %>

app/views/notes/edit.html.erb
<h1>Edit note</h1>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<%= link_to 'New note', new_note_path, class: 'btn btn-primary',
  data: { turbo_frame: dom_id(Note.new) } %>

<%= turbo_frame_tag Note.new %>

<%= tag.article id: 'notes', data: { controller: 'sortable' } do %>
  <%= render @notes %>
<% end %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form', note: @note %>

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.replace @note, render(@note) %>

app/views/shared/_errors.html.erb
<% if object&.errors&.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |k, v| %>
  <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
<% end %>